zookeeper:
  enabled: false

keeper:
  enabled: true
  resources:
    requests:
    cpu: 50m
    memory: 64Mi
  limit:
    cpu: 500m
    memory: 256Mi

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limit:
    cpu: 2000m
    memory: 4096Mi

persistence:
  enabled: true
  size: 10Gi

ingress:
  enabled: true
  ingressClassName: public
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
  hostname: clickhouse.resflow.ru
  extraTls:
    - secretName: clickhouse.resflow.ru-tls
      hosts:
        - clickhouse.resflow.ru

shards: 1
replicaCount: 1
