name: Build, push & deploy API

on:
  push:
    branches:
      - main
    paths:
      - api/**
      - .github/workflows/api.yaml

jobs:
  build-and-push:
    name: Build & push
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: registry.resflow.ru
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: docker/build-push-action@v6
        with:
          file: ./api/docker/dockerfile
          context: .
          push: true
          tags: registry.resflow.ru/api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - build-and-push

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-kubectl
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - run: kubectl apply -f "api/.kube/**"
      - run: |
          kubectl rollout -n resflow restart deployment api
          kubectl rollout -n resflow status deployment/api --timeout=300s
