name: Build, push & deploy parsers

on:
  push:
    branches:
      - main
    paths:
      - parsers/**
      - .github/workflows/parsers.yaml

jobs:
  build-and-push:
    name: Build & push
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: registry.resflow.ru
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - uses: ./.github/actions/setup-kubectl
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Up Prefect API proxy
        run: |
          kubectl port-forward -n prefect service/prefect-server 4200 &

      - uses: ./.github/actions/get-k8s-secret
        id: get-proxy-host
        with:
          secret: proxy-secrets
          namespace: resflow
          jsonpath: "{.data.proxy-host}"

      - uses: ./.github/actions/get-k8s-secret
        id: get-proxy-user
        with:
          secret: proxy-secrets
          namespace: resflow
          jsonpath: "{.data.proxy-user}"

      - uses: ./.github/actions/get-k8s-secret
        id: get-proxy-password
        with:
          secret: proxy-secrets
          namespace: resflow
          jsonpath: "{.data.proxy-password}"

      - uses: ./.github/actions/get-k8s-secret
        id: get-clickhouse-dsn
        with:
          secret: backend-env
          namespace: resflow
          jsonpath: "{.data.clickhouse_dsn}"

      - uses: ./.github/actions/get-k8s-secret
        id: get-amqp-dsn
        with:
          secret: backend-env
          namespace: resflow
          jsonpath: "{.data.amqp_dsn}"

      - uses: PrefectHQ/actions-prefect-deploy@v4
        with:
          all-deployments: true
          deployment-file-path: ./parsers/prefect.yaml
        env:
          PREFECT_IMAGE_NAME: registry.resflow.ru/parsers
          PREFECT_API_URL: http://127.0.0.1:4200/api
          PROXY_HOST: ${{ steps.get-proxy-host.outputs.value }}
          PROXY_USER: ${{ steps.get-proxy-user.outputs.value }}
          PROXY_PASSWORD: ${{ steps.get-proxy-password.outputs.value }}
          CLICKHOUSE_DSN: ${{ steps.get-clickhouse-dsn.outputs.value }}
          AMQP_DSN: ${{ steps.get-amqp-dsn.outputs.value }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - build-and-push

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-kubectl
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - run: kubectl apply -f "frontend/.kube/**"
      - run: |
          kubectl rollout -n resflow restart deployment frontend
          kubectl rollout -n resflow status deployment/frontend --timeout=300s
